site:
  name: Matyas Web Studio
  site: 'https://matyaswebstudio.com'
  base: '/'
  trailingSlash: false

#  googleSiteVerificationId: orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M

# Default SEO metadata
metadata:
  title:
    default: Matyas Web Studio
    template: '%s — Matyas Web Studio'
  description: 'Professzionális weboldal készítés vállalkozásoknak: gyors, mobilbarát és SEO-optimalizált céges weboldalak tervezése és fejlesztése, amelyek több érdeklődőt és ajánlatkérést hoznak.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Matyas Web Studio
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website

i18n:
  language: hu
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog' # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: 'G-8C71LR2P84'

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
